# Generated by Django 5.1 on 2024-09-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientInformation',
            new_name='ClientInformation',
        ),
    ]
