# Generated by Django 5.1 on 2024-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
