# Generated by Django 5.1 on 2024-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('sports', 'Sports'), ('health', 'Health'), ('beauty', 'Beauty')], max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('body_part', models.CharField(blank=True, choices=[('head', 'Head'), ('face', 'Face'), ('arms', 'Arms'), ('legs', 'Legs'), ('full_body', 'Full Body')], max_length=50, null=True)),
            ],
        ),
    ]
