# Generated by Django 5.1 on 2024-09-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_patientinformation_clientinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientInformation',
        ),
    ]
