# Generated by Django 5.1 on 2024-09-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
