# Generated by Django 5.1 on 2024-09-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_visit',
            new_name='date_of_registration',
        ),
    ]
