# Generated by Django 5.1 on 2024-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_date_of_visit_patient_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
