# Generated by Django 5.1 on 2024-09-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_rename_date_of_visit_patient_date_of_registration'),
        ('treatment', '0003_product_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(help_text='Enter time slot (e.g., 09:00 AM - 10:00 AM)', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.patient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.product')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.timeslot')),
            ],
        ),
    ]
