# Generated by Django 5.1 on 2024-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
